### PR TITLE
Add make_certs in specific directory

### PR DESCRIPTION
**Pull request by rymir**
Generate PEM certificates in a specific dir

### CODE REVIEW

**Comment by essen** [comment]
Please don't break indentation everywhere?

**Comment by rymir** [comment]
indentation should be good now

**Comment by essen** [comment]
Also remove the gitignore change please.

Looks fine otherwise.

**Comment by rymir** [comment]
ok, removed

**Comment by essen** [comment]
Bit late but I've merged it, thanks!

**Pull request closed without merging**
